### ISSUE TITLE
Add support to parse hexadecimal number in the generator regular expression

### ISSUE THREAD

**Issue by wxw-matt** [rioj7/regex-text-gen#2]
First, thanks for the development of this extension, it makes a lot of repeated work simple.

I believe this extension has already been able to generate hexadecimal with `radix`. I am thinking if it is possible to make it accept hexadecimal in the generator regular expression for the further calculation.

Here is an example:
The original text regex:
```
0x([a-fA-F0-9]+)
```
The generator regex:
```
{{=N[0]-0x123A}}
```
Thanks.

**Comment by rioj7** [comment]
@wxw-matt At the moment all capture groups are also tried to be a number (base-10) and results put in array `N`.

What I can do is also try to parse capture groups as Hex number and store result in array `H`.

If you have a better syntax let me know.

**Comment by rioj7** [comment]
@wxw-matt Just looked at the code. It uses `Number(s)`, and I tested with `Number('0x123')` and the result is 291.

So if you include the `0x` as part of the capture group it should work, you then have to put a `0x` in the generate regex as text like `0x{{=N[0]-0x123A:radix(16)}}`

But a solution that also works for hex numbers without prefix is still useful.

**Comment by rioj7** [comment]
@wxw-matt The problem is not `N[0]`. the whole matched text, like `0xFFAA` is parsed correct and put in `N[0]`. The problem is the part `0x123A`. The parser does not allow the characters `xa-fA-F` in the part for `{{=expr}}`.

I have modified the grammar to allow any JavaScript expression. If the expression uses unknown variables a different part will complain when the expression is evaluated.

Writing a few/a-lot unit tests and I will release the new version.

You can then convert any non `0x` prefixed hexadecimal number with `Number('0x'+C[1])`
`C` is an array of the capture group texts.

**Comment by rioj7** [comment]
@wxw-matt 

The start selection contains the hex number **with** the prefix `0x`

A possible solution is to first transform the selection to the calculation needed, in text with

`originalTextRegex` : `(.*)`
`generatorRegex` : `{{1}}-0x123A`

keep all selections the same and perform the following replacement

`originalTextRegex` : `(\w+)-(\w+)`
`generatorRegex` : `0x{{=N[1]-N[2]:radix(16)}}`

**Comment by wxw-matt** [comment]
@rioj7 thank you very much for the replies.
The approach in last reply is quite smart, it definitely works.
The workaround for me was I put the subtrahend as a decimal number.
Even though the number of the installation is not high, I would like to say this is an awesome VScode extension, and it can be used in quite many scenarios.

I am thinking if you'd like to make a GIF to help people understand how to use this extension.
I may have one and will send you (maybe late this week).

Thank you again.

**Comment by rioj7** [comment]
@wxw-matt  You can try v0.14.0

with your OP example you can now use

```none
{ "originalTextRegex": "([a-fA-F0-9]+)",
  "generatorRegex": "{{=Number('0x'+C[1])-0x123A:radix(16):ABC}}"
}
```

I'm not a big fan of GIF files for documentation. They bloat the extension size and most of the time the animation is so fast I can't see what is happening because the resolution is very bad. I have to look at the animation a lot. A few key screen shots with explanation usually works for me like they do it in a book [ ;-) old school documentation]. (I like the HTML variant of books)

A lot of people are scared off by regular expressions and looking at the readme of this extension it look even more complex ;-).

But once you see the possibilities you will use it a lot. I don't use all the syntax myself, but I know I can use these `{expr}` repeats when I need to generate dummy content.

The only thing I can do to make it more known is to use it in as many StackOverflow `[visual-studio-code]` questions as I can.

To reach the millions of VSC users I need to find a more aggressive marketing campaign. (?? Specific Facebook adds) I need to make a TikTok movie about Regular Expressions and make it go viral.

I have the same problem with **Remove Comments**. My version is a lot less buggy and applicable to more languages than the same named version with lots of installs but no longer maintained.

The same for the extension **File Templates**.
